on:
  push:
    branches:
      - master

jobs:
  upload-spec:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          repository: jack-hutchinson-cko/workflow-template
          token: ${{ secrets.PAT }}
      
      - uses: actions/upload-artifact@v2
        with:
          name: specification
          path: src/*
        
  publish-spec:
    runs-on: ubuntu-latest
    needs: upload-spec
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: specification
          path: spec

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: checkout/checkout-api-reference
          ref: ${{ github.event.pull_request.head.sha }}
          token: ${{ secrets.PAT }}
          path: src
          
      - name: Commit spec
        working-directory: src
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config user.name "$GITHUB_ACTOR"
          git branch -m "test-branch-ignore-me"
          cp -a ../spec/* spec/test
          git add .
          git commit -m 'Publish new API Specification'
          git push origin HEAD

      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.PAT}}
          script: |
            await github.pulls.create({
              owner: 'checkout',
              repo: 'checkout-api-reference',
              head: "test-branch-ignore-me",
              base: 'main',
              title: "Auto: Update API Specification"
            });

            
