on:
  push:
    branches:
      - master

jobs:
  upload-spec:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          repository: jack-hutchinson-cko/workflow-template
      
      - uses: actions/upload-artifact@v2
        with:
          name: specification
          path: spec/*
        
  publish-spec:
    runs-on: ubuntu-latest
    needs: upload-spec
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: specification
          path: src_spec

      - name: List
        run: ls

      - name: Fetch Checkout Api Reference repository
        uses: actions/checkout@v2
        with:
          repository: checkout/checkout-api-reference
          ref: development
          token: ${{ secrets.ACCESS_TOKEN }}
          path: src
          
      - name: Commit Api specification
        working-directory: src
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config user.name "$GITHUB_ACTOR"
          git branch -m "PRISM/Api-Spec"
          rsync -a ../src_spec/* spec/
          git add .
          git commit -m 'Publish new API Specification'
          git push origin HEAD

      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.ACCESS_TOKEN}}
          script: |
            await github.pulls.create({
              owner: 'checkout',
              repo: 'checkout-api-reference',
              head: "PRISM/Api-Spec",
              base: 'development',
              title: "PRISM: Update API Specification"
            });
