# This is a basic workflow to help you get started with Actions

on:
  push:
    branches:
      - 'master'

jobs:
  upload-spec:
    runs-on: ubuntu-latest
    steps:         
      - uses: actions/checkout@v2      
              
      - name: Move Team files to directory
        run: |
          echo ********** Created an empty folder ************
          mkdir newspec
          echo ********** Copying over what we need into the new folder ************
          mkdir -p newspec/components/schemas
          cp -r spec/components/schemas/TEAM newspec/components/schemas
          mkdir -p newspec/paths
          cp spec/paths/TEAM*.* newspec/paths          
          echo ********** Listing contents of newspec/ ************
          ls spec/*/**          
          echo ********** Ready to upload specs ************
          
      - uses: actions/upload-artifact@v2
        with:
          name: specification
          path: newspec/
        
  publish-spec:
    runs-on: ubuntu-latest
    needs: upload-spec
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: specification
          path: src_spec

      - name: Fetch Checkout Api Reference repository
        uses: actions/checkout@v2
        with:
          repository: checkout/checkout-api-reference
          ref: development
          token: ${{ secrets.PAT }}
          path: src
          
      - name: Commit Api specification
        working-directory: src
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config user.name "$GITHUB_ACTOR"
          git branch -m "TEAM/Api-Spec"
          rsync -a ../src_spec/ spec/
          git add .
          git commit -m 'Publish new API Specification'
          git push origin HEAD

      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.PAT}}
          script: |
            await github.pulls.create({
              owner: 'checkout',
              repo: 'checkout-api-reference',
              head: "TEAM/Api-Spec",
              base: 'development',
              title: "TEAM: Update API Specification"
            });
